


#Call the two libraries that will enable the use log and generating a random number
import random
import math

print("""This is a number guessing game. The system will generate a random integer number and you have to guess what that number is.
The number lies between a lower limit and an upper limit that you define.""")


print("****************************************************************************************************************************")        
print("****************************************************************************************************************************")   

#Getting user input

lowerlimit = int(input("Please enter the lower limit : "))
upperlimit = int(input("Please enter the upper limit : "))

scope = range(lowerlimit,upperlimit)
randomnumber = random.randint(lowerlimit, upperlimit)
maxtries = round((math.log((upperlimit-lowerlimit+1),2)),0)

print("You have a total of ", maxtries , " tries " )

count = 0

#Loop the input
while count <= maxtries:
    
    guess = int(input("Guess the number generated by the system : "))
    
    if guess ==  randomnumber:
        print("Congragulation, you have gussed correctly  ")
        break 
         
    elif guess > randomnumber:
        print("\n The number you entered is bigger than the random number ")
        count = count + 1
        
    elif guess < randomnumber:
        print("\n The number you entered is less than the random number ")
        count = count + 1
      
    
if count > maxtries:
    print("You have run out of tries ") 
        

print("****************************************************************************************************************************")        
print("****************************************************************************************************************************")